<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MncfaRS' shared service.

return $this->privates['.service_locator.MncfaRS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'token' => ['privates', '.errored..service_locator.MncfaRS.Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage', NULL, 'Cannot autowire service ".service_locator.MncfaRS": it references class "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage" but no such service exists. Try changing the type-hint to "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface" instead.'],
]);
