<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v0RCX1Z' shared service.

return $this->privates['.service_locator.v0RCX1Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'documentRepository' => ['privates', 'AppBundle\\Repository\\DocumentRepository', 'getDocumentRepositoryService.php', true],
    'documentTypeRepository' => ['privates', 'AppBundle\\Repository\\DocumentTypeRepository', 'getDocumentTypeRepositoryService.php', true],
    'projectRepository' => ['privates', 'AppBundle\\Repository\\ProjectRepository', 'getProjectRepositoryService.php', true],
    'userProjectRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserProjectRepository', 'getUserProjectRepositoryService.php', true],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
