<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mNaWj9j' shared service.

return $this->privates['.service_locator.mNaWj9j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authorizationChecker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'messageRepository' => ['privates', 'AppBundle\\Repository\\MessageRepository', 'getMessageRepositoryService.php', true],
    'messageTypeRepository' => ['privates', 'AppBundle\\Repository\\MessageTypeRepository', 'getMessageTypeRepositoryService.php', true],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
