<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.g_h.b6l' shared service.

return $this->privates['.service_locator.g_h.b6l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authorizationChecker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'damageDocumentRepository' => ['privates', 'Main\\InsuranceBundle\\Repository\\DamageDocumentRepository', 'getDamageDocumentRepositoryService.php', true],
    'damageRepository' => ['privates', 'Main\\InsuranceBundle\\Repository\\DamageRepository', 'getDamageRepositoryService.php', true],
    'documentRepository' => ['privates', 'AppBundle\\Repository\\DocumentRepository', 'getDocumentRepositoryService.php', true],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
