<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AihCWxh' shared service.

return $this->privates['.service_locator.AihCWxh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'bankAccountRepository' => ['privates', 'Main\\UserBundle\\Repository\\BankAccountRepository', 'getBankAccountRepositoryService.php', true],
    'countryRepository' => ['privates', 'Main\\UserBundle\\Repository\\CountryRepository', 'getCountryRepositoryService.php', true],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
