<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Tle4ytK' shared service.

return $this->privates['.service_locator.Tle4ytK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'achievementRepository' => ['privates', 'Main\\UserBundle\\Repository\\AchievementRepository', 'getAchievementRepositoryService.php', true],
    'addressRepository' => ['privates', 'Main\\UserBundle\\Repository\\AddressRepository', 'getAddressRepositoryService.php', true],
    'bankAccountRepository' => ['privates', 'Main\\UserBundle\\Repository\\BankAccountRepository', 'getBankAccountRepositoryService.php', true],
    'jobGroupRepository' => ['privates', 'Main\\UserBundle\\Repository\\JobGroupRepository', 'getJobGroupRepositoryService.php', true],
    'tariffRepository' => ['privates', 'Main\\InsuranceBundle\\Repository\\TariffRepository', 'getTariffRepositoryService.php', true],
    'titleRepository' => ['privates', 'Main\\UserBundle\\Repository\\TitleRepository', 'getTitleRepositoryService.php', true],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
