<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Wcj7vZk' shared service.

return $this->privates['.service_locator.Wcj7vZk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'event' => ['privates', '.errored..service_locator.Wcj7vZk.Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent', NULL, 'Cannot autowire service ".service_locator.Wcj7vZk": it references class "Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent" but no such service exists.'],
]);
