<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wbYV.pu' shared service.

return $this->privates['.service_locator.wbYV.pu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
    'securityLogRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserSecurityLogRepository', 'getUserSecurityLogRepositoryService.php', true],
    'tokenStorage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
