<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1x3ZQFJ' shared service.

return $this->privates['.service_locator.1x3ZQFJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'animalDogBreedRepository' => ['privates', 'Main\\AdminBundle\\Repository\\AnimalDogBreedRepository', 'getAnimalDogBreedRepositoryService.php', true],
    'authorizationChecker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
