<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CSp2n.F' shared service.

return $this->privates['.service_locator.CSp2n.F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'securityLog' => ['privates', '.errored..service_locator.CSp2n.F.Main\\UserBundle\\Entity\\UserSecurityLog', NULL, 'Cannot autowire service ".service_locator.CSp2n.F": it references class "Main\\UserBundle\\Entity\\UserSecurityLog" but no such service exists.'],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
