<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.14cPno6' shared service.

return $this->privates['.service_locator.14cPno6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'titleRepository' => ['privates', 'Main\\UserBundle\\Repository\\TitleRepository', 'getTitleRepositoryService.php', true],
    'userActivityRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserActivityRepository', 'getUserActivityRepositoryService.php', true],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
