<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nRTkUFf' shared service.

return $this->privates['.service_locator.nRTkUFf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'activityRepository' => ['privates', 'Main\\UserBundle\\Repository\\ActivityRepository', 'getActivityRepositoryService.php', true],
    'userRepository' => ['privates', 'Main\\UserBundle\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
