<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Main\UserBundle\Security\Voter\DoAdminImportVoter' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/VoterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/Voter.php';
include_once $this->targetDirs[3].'/src/Main/UserBundle/Security/Voter/DoAdminImportVoter.php';

if ($lazyLoad) {
    return $this->privates['Main\UserBundle\Security\Voter\DoAdminImportVoter'] = $this->createProxy('DoAdminImportVoter_13f287c', function () {
        return \DoAdminImportVoter_13f287c::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getDoAdminImportVoterService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Main\UserBundle\Security\Voter\DoAdminImportVoter(($this->privates['security.helper'] ?? $this->load('getSecurity_HelperService.php')));
