<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.extension' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';

return $this->privates['form.extension'] = new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'AppBundle\\Form\\Message\\EditMessageFormType' => ['privates', 'AppBundle\\Form\\Message\\EditMessageFormType', 'getEditMessageFormTypeService.php', true],
    'AppBundle\\Form\\Project\\EditProjectFormType' => ['privates', 'AppBundle\\Form\\Project\\EditProjectFormType', 'getEditProjectFormTypeService.php', true],
    'AppBundle\\Form\\Type\\TagFormType' => ['privates', 'AppBundle\\Form\\Type\\TagFormType', 'getTagFormTypeService.php', true],
    'Main\\InsuranceBundle\\Form\\Company\\Admin\\EditCompanyFormType' => ['privates', 'Main\\InsuranceBundle\\Form\\Company\\Admin\\EditCompanyFormType', 'getEditCompanyFormTypeService.php', true],
    'Main\\InsuranceBundle\\Form\\Company\\Admin\\NewCompanyFormType' => ['privates', 'Main\\InsuranceBundle\\Form\\Company\\Admin\\NewCompanyFormType', 'getNewCompanyFormTypeService.php', true],
    'Main\\InsuranceBundle\\Form\\Contract\\EditContractFormType' => ['privates', 'Main\\InsuranceBundle\\Form\\Contract\\EditContractFormType', 'getEditContractFormTypeService.php', true],
    'Main\\InsuranceBundle\\Form\\Tariff\\Admin\\EditTariffFormType' => ['privates', 'Main\\InsuranceBundle\\Form\\Tariff\\Admin\\EditTariffFormType', 'getEditTariffFormTypeService.php', true],
    'Main\\InsuranceBundle\\Form\\Tariff\\Admin\\NewTariffFormType' => ['privates', 'Main\\InsuranceBundle\\Form\\Tariff\\Admin\\NewTariffFormType', 'getNewTariffFormTypeService.php', true],
    'Main\\UserBundle\\Form\\Address\\Admin\\EditAddressFormType' => ['privates', 'Main\\UserBundle\\Form\\Address\\Admin\\EditAddressFormType', 'getEditAddressFormTypeService.php', true],
    'Main\\UserBundle\\Form\\Address\\Admin\\NewAddressFormType' => ['privates', 'Main\\UserBundle\\Form\\Address\\Admin\\NewAddressFormType', 'getNewAddressFormTypeService.php', true],
    'Main\\UserBundle\\Form\\Bank\\Admin\\EditBankFormType' => ['privates', 'Main\\UserBundle\\Form\\Bank\\Admin\\EditBankFormType', 'getEditBankFormTypeService.php', true],
    'Main\\UserBundle\\Form\\Bank\\Admin\\NewBankFormType' => ['privates', 'Main\\UserBundle\\Form\\Bank\\Admin\\NewBankFormType', 'getNewBankFormTypeService.php', true],
    'Main\\UserBundle\\Form\\LoginForm' => ['privates', 'Main\\UserBundle\\Form\\LoginForm', 'getLoginFormService.php', true],
    'Main\\UserBundle\\Form\\NewsletterFormType' => ['privates', 'Main\\UserBundle\\Form\\NewsletterFormType', 'getNewsletterFormTypeService.php', true],
    'Main\\UserBundle\\Form\\RegistrationForm' => ['privates', 'Main\\UserBundle\\Form\\RegistrationForm', 'getRegistrationFormService.php', true],
    'Main\\UserBundle\\Form\\UserRegistrationForm' => ['privates', 'Main\\UserBundle\\Form\\UserRegistrationForm', 'getUserRegistrationFormService.php', true],
    'Main\\UserBundle\\Form\\User\\Admin\\EditUserFormType' => ['privates', 'Main\\UserBundle\\Form\\User\\Admin\\EditUserFormType', 'getEditUserFormTypeService.php', true],
    'Main\\UserBundle\\Form\\User\\Admin\\NewUserFormType' => ['privates', 'Main\\UserBundle\\Form\\User\\Admin\\NewUserFormType', 'getNewUserFormTypeService.php', true],
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['AppBundle\Form\TypeExtension\HelpFormExtension'] ?? $this->load('getHelpFormExtensionService.php'));
    yield 1 => ($this->privates['form.type_extension.form.transformation_failure_handling'] ?? $this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 2 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 3 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 4 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 5 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
}, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? ($this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? ($this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
    yield 1 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
}, 2));
