<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Main\UserBundle\Doctrine\HashPasswordListener' shared autowired service.

include_once $this->targetDirs[3].'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
include_once $this->targetDirs[3].'/src/Main/UserBundle/Doctrine/HashPasswordListener.php';

if ($lazyLoad) {
    return $this->privates['Main\UserBundle\Doctrine\HashPasswordListener'] = $this->createProxy('HashPasswordListener_2e8e646', function () {
        return \HashPasswordListener_2e8e646::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getHashPasswordListenerService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Main\UserBundle\Doctrine\HashPasswordListener(($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')));
