<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.cache_naming_strategy' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Naming/PropertyNamingStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Naming/CacheNamingStrategy.php';

return $this->privates['jms_serializer.cache_naming_strategy'] = new \JMS\Serializer\Naming\CacheNamingStrategy(($this->privates['jms_serializer.serialized_name_annotation_strategy'] ?? $this->load('getJmsSerializer_SerializedNameAnnotationStrategyService.php')));
