<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Main\UserBundle\Form\Address\Admin\NewAddressFormType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Main/UserBundle/Form/Address/Admin/NewAddressFormType.php';

if ($lazyLoad) {
    return $this->privates['Main\UserBundle\Form\Address\Admin\NewAddressFormType'] = $this->createProxy('NewAddressFormType_ffe9ca1', function () {
        return \NewAddressFormType_ffe9ca1::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getNewAddressFormTypeService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Main\UserBundle\Form\Address\Admin\NewAddressFormType();
