<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Main\UserBundle\Form\Bank\Admin\NewBankFormType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Main/UserBundle/Form/Bank/Admin/NewBankFormType.php';

if ($lazyLoad) {
    return $this->privates['Main\UserBundle\Form\Bank\Admin\NewBankFormType'] = $this->createProxy('NewBankFormType_c796b38', function () {
        return \NewBankFormType_c796b38::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getNewBankFormTypeService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Main\UserBundle\Form\Bank\Admin\NewBankFormType();
