<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Main\InsuranceBundle\Form\Company\Admin\NewCompanyFormType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Main/InsuranceBundle/Form/Company/Admin/NewCompanyFormType.php';

if ($lazyLoad) {
    return $this->privates['Main\InsuranceBundle\Form\Company\Admin\NewCompanyFormType'] = $this->createProxy('NewCompanyFormType_af86ebd', function () {
        return \NewCompanyFormType_af86ebd::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getNewCompanyFormTypeService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Main\InsuranceBundle\Form\Company\Admin\NewCompanyFormType();
