<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.CSp2n.F.Main\UserBundle\Entity\UserSecurityLog' shared service.

include_once $this->targetDirs[3].'/src/Main/UserBundle/Entity/UserSecurityLog.php';

return $this->privates['.errored..service_locator.CSp2n.F.Main\UserBundle\Entity\UserSecurityLog'] = new \Main\UserBundle\Entity\UserSecurityLog();
