parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            AppBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AppBundle/Entity'
                prefix: 'AppBundle\Entity'
                alias: AppBundle
            AdminBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Main/AdminBundle/Entity'
                prefix: 'Main\AdminBundle\Entity'
                alias: AdminBundle
            UserBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Main/UserBundle/Entity'
                prefix: 'Main\UserBundle\Entity'
                alias: UserBundle
            InsuranceBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Main/InsuranceBundle/Entity'
                prefix: 'Main\InsuranceBundle\Entity'
                alias: InsuranceBundle