# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    host:             smtp.gmail.com
    transport:        gmail
    encryption:       tls
    auth-mode:        login
    username:         andre.rust@intertects.com
    password:         Jari.1010
    port:             465
