<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2b7hBn5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2b7hBn5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2b7hBn5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2b7hBn5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2b7hBn5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2b7hBn5',
    'container.build_id' => '7de8fcbe',
    'container.build_time' => 1550404364,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2b7hBn5');
